#!/bin/sh
#
# An test hook script to integrate with git to test the virtual file system.
#
# The hook is passed a version (currently 1) and outputs to stdout all files
# that git should paid attention to.  Paths must be relative to the root of
# the working tree and separated by a single NUL.
#

if test "$#" -ne 1
then
	echo "$0: exactly 1 argument expected" >&2
	exit 2
fi

if test "$1" != 1
then
	echo "Unsupported core.virtualfilesystem hook version." >&2
	exit 1
fi

#find -type f -printf '%P\0'
find -type d -printf '%P/\0'
